version: "3.9"

services:
  api:
    build: ./api
    container_name: rag_api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./api:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
      - qdrant

  worker:
    build: ./worker
    container_name: rag_worker
    command: python worker.py
    volumes:
      - ./worker:/app
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
      - qdrant

  postgres:
    image: postgres:15
    container_name: rag_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: rag_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  qdrant:
    image: qdrant/qdrant:v1.8.1
    container_name: rag_qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  pg_data:
  redis_data:
  qdrant_data: